_target_: src.model.LenslessReconstructor
n_iters: 5
admm_trainable: true
pre_processor:
  _target_: src.model.DRUNet
  channels: [32, 64, 116, 128]
  n_blocks: 4
post_processor:
  _target_: src.model.DRUNet
  channels: [32, 64, 116, 128]
  n_blocks: 4
