_target_: src.logger.CometMLWriter
project_name: "lensless"
workspace: null
run_name: "lensless"
mode: "online"
loss_names: ["loss", "mse_loss", "lpips_loss"] # which losses to log
log_checkpoints: False # set to True if you want to log save_dir with checkpoints
id_length: 32 # length of the run_id
